# Generated by Django 5.2.7 on 2026-07-12 11:32

import cloudinary.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parents', '0004_alter_child_image'),
        ('users', '0006_customuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'صورة'), ('video', 'فيديو')], max_length=10, verbose_name='نوع الوسائط')),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='الملف')),
                ('caption', models.TextField(blank=True, default='', verbose_name='التعليق')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('children', models.ManyToManyField(blank=True, related_name='memories', to='parents.child', verbose_name='الأطفال')),
                ('students', models.ManyToManyField(blank=True, related_name='memories', to='users.studentuser', verbose_name='الطلاب')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_memories', to='users.instructor', verbose_name='تم الرفع بواسطة')),
            ],
            options={
                'verbose_name': 'ذكرى',
                'verbose_name_plural': 'الذكريات',
                'ordering': ['-created_at'],
            },
        ),
    ]
