"""
Django settings for Redwan_courses_center project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path
from decouple import config, Csv
import cloudinary
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Uses python-decouple: reads from .env file locally, or environment variables in Docker
SECRET_KEY = config("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

# ALLOWED_HOSTS from comma-separated string
ALLOWED_HOSTS = config("DJANGO_ALLOWED_HOSTS", default="127.0.0.1", cast=Csv())

# Render.com deployment: Add the external hostname
RENDER_EXTERNAL_HOSTNAME = config("RENDER_EXTERNAL_HOSTNAME", default=None)
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    # "simpleui",  # MUST be first
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "django_filters",
    "djoser",
    'corsheaders',
    "django_crontab",
    "channels",
    "cloudinary_storage",
    "cloudinary",
    "users",
    "parents",
    "attendance",
    "core",
    "courses",
    "enrollments_payments",
    "memories",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # white noise middleware
    "whitenoise.middleware.WhiteNoiseMiddleware",
    # CORS must be before CommonMiddleware
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # 'django.middleware.locale.LocaleMiddleware',  # ← ADD THIS
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# CORS settings - Allow all origins for API testing (no frontend yet)
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = "Redwan_courses_center.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR, os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Redwan_courses_center.wsgi.application"
ASGI_APPLICATION = "core.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Check for Render's DATABASE_URL first (production)
DATABASE_URL = config("DATABASE_URL", default=None)

if DATABASE_URL:
    # Render provides DATABASE_URL - parse it with dj-database-url
    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Local development - use individual env vars
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.{}".format(
                config("DATABASE_ENGINE", default="sqlite3")
            ),
            "NAME": config("DATABASE_NAME", default="db.sqlite3"),
            "USER": config("DATABASE_USERNAME", default=""),
            "PASSWORD": config("DATABASE_PASSWORD", default=""),
            "HOST": config("DATABASE_HOST", default="127.0.0.1"),
            "PORT": config("DATABASE_PORT", default=5432, cast=int),
        }
    }
INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    "localhost",
    "0.0.0.0",
    # ...
]

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ar"

LANGUAGES = [
    ("ar", "العربية"),
    ("en", "English"),
]
LANGUAGE_BIDI = True
USE_I18N = True
USE_L10N = True
USE_TZ = True

TIME_ZONE = "Africa/Cairo"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# WhiteNoise configuration for serving static files in production
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Cloudinary Configuration
CLOUDINARY_STORAGE = {
    "CLOUD_NAME": config("CLOUDINARY_CLOUD_NAME", default=""),
    "API_KEY": config("CLOUDINARY_API_KEY", default=""),
    "API_SECRET": config("CLOUDINARY_API_SECRET", default=""),
}

# Configure Cloudinary
cloudinary.config(
    cloud_name=CLOUDINARY_STORAGE["CLOUD_NAME"],
    api_key=CLOUDINARY_STORAGE["API_KEY"],
    api_secret=CLOUDINARY_STORAGE["API_SECRET"],
)

# Use Cloudinary for media storage
DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"

""" # Specify simpleui's default theme, specify a filename, and the relative path is read from simpleui's theme directory
SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'
SIMPLEUI_HOME_TITLE = 'My Home Title'
SIMPLEUI_CONFIG = {
    "system_keep": False,
    "rtl": True,
    # Branding
    
    "system_name": "لوحة إدارة واحة الرضوان",
    "system_title": "Redwan Courses Center",
    "system_icon": "fas fa-chalkboard-teacher",

    # Welcome text
    "welcome_sign": "مرحبًا بك في لوحة الإدارة",

    # Copyright
    "copyright": "Redwan Courses Center © 2025",

    # Whether to enable animations
    "animation": True,

    # Show language switcher
    "language": True,

    # Default home page
    "home_page": "/Al-Redwan-superadmin-dashboard/",

    # Disable UI builder for production stability
    "dynamic": False,
}

SIMPLEUI_ICON = {
    'System_Manage': 'fab fa-apple',
    'Employeee_Manage': 'fas fa-user-tie'
} """
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "users.CustomUser"

CRONJOBS = [
    # Cron Format: minute hour day month weekday, 0 = Sunday here
    # Every Sunday at 00:05 AM - Generate attendance records for the week
    ("5 0 * * 0", "attendance.cron.generate_instructor_attendance_weekly"),
    # Every day at 23:59 - Mark absent for today
    ("59 23 * * *", "attendance.cron.mark_absent_daily"),
    # Every day at 00:01 - Fallback to mark absent for yesterday
    ("1 0 * * *", "attendance.cron.mark_absent_for_yesterday"),
    # Every day at 06:00 - Log today's expected attendance
    ("0 6 * * *", "attendance.cron.update_pending_to_not_started"),
]


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [config("REDIS_URL", default="redis://redis:6379")],
        },
    },
}


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PAGINATION_CLASS": "core.utils.pagination.CustomPageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.OrderingFilter",
    ],
}


SIMPLE_JWT = {
    "AUTH_HEADER_TYPES": ("JWT",),
    "ACCESS_TOKEN_LIFETIME": timedelta(days=99),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}


# Djoser configuration for phone number authentication
DJOSER = {
    # Use phone_number1 as the login field
    "LOGIN_FIELD": "phone_number1",
    # Require re_password on registration
    "USER_CREATE_PASSWORD_RETYPE": True,
    # Require current password and retype on password change
    "SET_PASSWORD_RETYPE": True,
    # Custom serializers - IMPORTANT for security!
    # Prevents users from setting is_staff, is_superuser, role via API
    "SERIALIZERS": {
        "user_create": "users.serializers.CustomUserCreateSerializer",
        "user_create_password_retype": "users.serializers.CustomUserCreateSerializer",
        "user": "users.serializers.CustomUserSerializer",
        "current_user": "users.serializers.CustomUserSerializer",
    },
    # Permissions
    "PERMISSIONS": {
        "user": ["rest_framework.permissions.IsAuthenticated"],
        "user_list": ["rest_framework.permissions.IsAdminUser"],
    },
    # Hide sensitive user IDs from non-admin users
    "HIDE_USERS": True,
}

# Production Security Settings
if not DEBUG:
    # HTTPS/SSL settings
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # HSTS settings
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Cookie settings
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Additional security headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = "DENY"

    # CSRF trusted origins for Render - build from RENDER_EXTERNAL_HOSTNAME
    if RENDER_EXTERNAL_HOSTNAME:
        CSRF_TRUSTED_ORIGINS = [f"https://{RENDER_EXTERNAL_HOSTNAME}"]
    else:
        CSRF_TRUSTED_ORIGINS = config(
            "CSRF_TRUSTED_ORIGINS",
            default="https://localhost",
            cast=Csv()
        )
