export * from "./common";
export * from "./attendance";
export * from "./courses";
export * from "./enrollments";
export * from "./instructors";
export * from "./lectures";
export * from "./people";
export * from "./staff-attendance";
export * from "./memories";
