# Generated by Django 5.2.7 on 2026-10-07 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_landingpagecourse_course'),
        ('courses_online', '0001_initial'),
        ('parents', '0004_alter_child_image'),
        ('users', '0007_parentonlinecourserating_studentonlinecourserating'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentinstructorrating',
            name='online_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_instructor_ratings', to='courses_online.onlinecourse', verbose_name='الدورة الإلكترونية'),
        ),
        migrations.AddField(
            model_name='studentinstructorrating',
            name='online_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_instructor_ratings', to='courses_online.onlinecourse', verbose_name='الدورة الإلكترونية'),
        ),
        migrations.AlterField(
            model_name='parentinstructorrating',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_instructor_ratings', to='courses.course', verbose_name='الدورة'),
        ),
        migrations.AlterField(
            model_name='studentinstructorrating',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_instructor_ratings', to='courses.course', verbose_name='الدورة'),
        ),
        migrations.AddConstraint(
            model_name='parentinstructorrating',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', False), ('online_course__isnull', True)), models.Q(('course__isnull', True), ('online_course__isnull', False)), _connector='OR'), name='parent_instructor_rating_one_course'),
        ),
        migrations.AddConstraint(
            model_name='studentinstructorrating',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', False), ('online_course__isnull', True)), models.Q(('course__isnull', True), ('online_course__isnull', False)), _connector='OR'), name='student_instructor_rating_one_course'),
        ),
    ]
