# Generated by Django 5.2.7 on 2026-09-26 20:58

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='العنوان')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='وصف قصير')),
                ('video_url', models.URLField(blank=True, help_text='YouTube أو Vimeo أو Bunny أو رابط mp4 مباشر. اتركه فارغاً لو رفعت ملفاً.', max_length=500, verbose_name='رابط الفيديو')),
                ('video_file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='ملف الفيديو')),
                ('poster', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة الغلاف')),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='تظهر كشارة على الفيديو، مثال 90 = 1:30', verbose_name='المدة بالثواني')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='ظاهر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فيديو الصفحة الرئيسية',
                'verbose_name_plural': 'فيديوهات الصفحة الرئيسية',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
